### ISSUE TITLE
[QUESTION]: Persistent volume not getting detached after pod deletion

### ISSUE THREAD

**Issue by rajendraindukuri** [dell/csm#107]
**Reported by customer :** 
I have a problem with csi-unity - once a PersistentVolume is attached to a node, it does not get detached after the pod using it is deleted
later on, when a different pod referring to that PV via PersistentVolumeClaim gets scheduled to a different node, CSI driver creates new VolumeAttachment which cannot be provisioned: `Volume has been published to a different host already`.

**Comment by karthikk92** [comment]
could you please let us know the bellow details
1. environment info
2.driver version
3. installed via helm/operator  ? its version ?
4.  k8s/openshift version

**Comment by mkej** [comment]
1. Deployed on a VM-based Kubernetes cluster, each VM runs Ubuntu 20.04 with 5.11 kernel.
2. Observed on `v1.6.0` and `v2.6.0`
3. Installed via Helm, using `dell-csi-helm-installer/csi-install.sh` script.
4. K8s cluster installed using `kubeadm`, issues observed on `v1.21.3` and `v1.22.4` (same cluster, upgraded)
5. Steps to reproduce:
Apply these resources to cluster:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: unity-iscsi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: volume-test
  labels:
    app: volume-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-test
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: volume-test
      volumes:
      - name: volume-test
        persistentVolumeClaim:
          claimName: volume-test
```
This will create `PersistentVolume` and a `VolumeAttachment` for it and a specific node.

In order to force rescheduling pod to a different node, add `spec.template.spec.nodeName: some-different-node` to the `ReplicaSet` and delete existing pod.

Another `VolumeAttachment` will be created, with the previous one still in place, with `status.attachError.message = 'rpc error: code = Aborted desc =  runid=7652 Volume has been published to a different host already.'`. The previous attachement is still in place and active. This will keep the `Pod` stuck with `AttachVolume.Attach failed` error from `attachdetach-controller`.
