### ISSUE TITLE
[BUG]: CSM Operator offline install powerflex csi driver sidecar trying to pull from registry.k8s.io

### ISSUE THREAD

**Issue by anurajpd** [dell/csm#1094]
### Bug Description

CSM Operator offline install powerflex csi driver sidecar trying to pull from registry.k8s.io

### Logs

Below is the list of images from the powerflex csi driver controller pod 

[anuraj@adm01 data]$ oc get pod powerflex-controller-7dd74965d5-s6ncm -n dell-csm-powerflex -oyaml | grep -i image:
    image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
    image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
    image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2
    image: registry.k8s.io/sig-storage/csi-resizer:v1.9.2
    image: harbor01.vdi.xtremio/dell-csm-operator/csi-vxflexos:v2.9.0
    image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
    image: harbor01.vdi.xtremio/dell-csm-operator/csi-vxflexos:v2.9.0
    image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
    image: registry.k8s.io/sig-storage/csi-resizer:v1.9.2
    image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2

### Steps to Reproduce

deploy the csm operator offline and try to create csm for powerflex

### Expected Behavior

csi driver side car images should be pulled from local registry.cd csm

### CSM Driver(s)

csm powerflex v290

### Installation Type

Operator v1.4.0

### Container Orchestrator

Openshift 4.14.6

### Operating System

CoreOS

**Comment by shanmydell** [comment]
@adarsh-dell : Please look into this issue

**Comment by AkshaySainiDell** [comment]
Looking into it.

**Comment by AkshaySainiDell** [comment]
It looks like the images of sideCars are currently missing in the sample yamls. As a consequence, the csm-operator is pulling them from registry.k8s.io.
To address this, we recommend implementing a workaround: manually update the images of sideCars in `storage_csm_powerflex_v290.yaml` file before proceeding with the driver installation.

```
    sideCars:
    # 'k8s' represents a string prepended to each volume created by the CSI driver
      - name: provisioner
        image: <localregistry>/csi-provisioner:v3.6.2                                                                                                                                                                                  
        args: ["--volume-name-prefix=k8s"]
      - name: attacher                                                                                                                                                                                                                                                      
        image: <localregistry>/csi-attacher:v4.4.2                                                                                                                                                                                     
      - name: registrar                                                                                                                                                                                                                                                     
        image: <localregistry>/csi-node-driver-registrar:v2.9.1                                                                                                                                                                        
      - name: resizer                                                                                                                                                                                                                                                       
        image: <localregistry>/csi-resizer:v1.9.2                                                                                                                                                                                      
      - name: snapshotter                                                                                                                                                                                                                                                   
        image: <localregistry>/csi-snapshotter:v6.3.2

    # sdc-monitor is disabled by default, due to high CPU usage
      - name: sdc-monitor
        enabled: false
        image: <localregistry>/sdc:4.5
        envs:
        - name: HOST_PID
          value: "1"
        - name: MDM
          value: "10.xx.xx.xx,10.xx.xx.xx" #do not add mdm value here if it is present in secret

    # health monitor is disabled by default, refer to driver documentation before enabling it
    # Also set the env variable controller.envs.X_CSI_HEALTH_MONITOR_ENABLED  to "true".
      - name: csi-external-health-monitor-controller
        enabled: false
        image: <localregistry>/csi-external-health-monitor-controller:v0.10.0
        args: ["--monitor-interval=60s"]
```
