### ISSUE TITLE
[BUG]: csi-powerstore can't fetch metrics of nfs PVCs

### ISSUE THREAD

**Issue by druesendieb** [dell/csm#1367]
### Bug Description

We're currently migrating from a Unity to Powerstore storage system, so we have a cluster with both csi-unity and csi-powerstore drivers installed. With both we use nfs and iscsi storage classes.  

After implementing the csi-powerstore driver and migrating the first PVCs, we encountered an issue with the published nfs PVC metrics, instead of fetching them we face errors in the driver container of the node daemonset. 

Metrics from powerstore-iscsi and unity-nfs work as expected. 

### Logs

{"level":"info","msg":"/csi.v1.Node/NodeGetVolumeStats: REQ 0018: VolumeId=66866727-cf7a-4dd8-b15f-16ad14c055a8/PS4f022082b83d/nfs, VolumePath=/var/lib/kubelet/pods/e73489b6-17cf-4e78-bcde-59430aa8baea/volumes/kubernetes.io~csi/csivol-$NAME-cf0e8041e2/mount, XXX_NoUnkeyedLiteral={}, XXX_sizecache=0","time":"2024-07-05T11:11:19.602727737Z"}

{"level":"info","msg":"/csi.v1.Node/NodeGetVolumeStats: REP 0018: VolumeCondition=abnormal:true message:\"host csi-node-a122dec52e994b51bb2c21ee0113800e-$IP is not attached to NFS export for filesystem 66866727-cf7a-4dd8-b15f-16ad14c055a8\" , XXX_NoUnkeyedLiteral={}, XXX_sizecache=0","time":"2024-07-05T11:11:19.615126687Z"}

### Additional Environment Information

k8s 1.24

### Steps to Reproduce

Configure csi-powerstore with Volume Health Monitoring enabled
https://dell.github.io/csm-docs/v3/csidriver/installation/helm/powerstore/#volume-health-monitoring

Use NFS storageclass:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "powerstore-nfs"
provisioner: "csi-powerstore.dellemc.com"
parameters:
  arrayID: "$ARRAY"
  csi.storage.k8s.io/fstype: "nfs"
  nasName: "$NAME"
  allowRoot: "root"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

Create 1 PVC with nfs storage class
Create Pod consuming this PVC

See errors in csi-powerstore-node driver container when fetching metrics

### Expected Behavior

No errors when running NodeGetVolumeStats
Kubernetes should present volume metrics from nfs volumes 

### CSM Driver(s)

csi-powerstore: 2.10.0

### Installation Type

Helm

### Container Orchestrator

RKE1

### Operating System

Ubuntu 18.04
