### ISSUE TITLE
[BUG]: CSI-PowerStore Node Prefix is ignored

### ISSUE THREAD

**Issue by suryagupta4** [dell/csm#1458]
### Bug Description

During the installation of the CSI PowerStore with the CSM Operator, I set the variable:

```
common:
  envs:      
    - name: X_CSI_POWERSTORE_NODE_NAME_PREFIX
      value: ocp-dk01
```

If existing node had a different prefix, the new node in Kubernetes will be incorrectly updated as below. Also, the new prefix is ignored.

```
spec:
  drivers:
  - name: csi-powerstore.dellemc.com
    nodeID: csi-node-5c3d7fd0eb004604a6036df6eb4853ed-w.x.y.z-w.x.y.z
```

This prevents to mount volumes with the error :

> AttachVolume.Attach failed for volume "ocp-3f9e6a6c00" : rpc error: code = NotFound desc = host with k8s node ID 'csi-node-9a7687da85fb4186b48230878bbfc939-w.x.y.z-w.x.y.z' not found

### Logs

AttachVolume.Attach failed for volume "ocp-3f9e6a6c00" : rpc error: code = NotFound desc = host with k8s node ID 'csi-node-9a7687da85fb4186b48230878bbfc939-w.x.y.z-w.x.y.z' not found

### Steps to Reproduce

Install the driver with default prefix.
Update the driver sample yaml to use a different prefix.
Re-install the driver with the updated prefix.

### Expected Behavior

The host entry should be modified with the correct name having the updated prefix. Also, the node id in kubernetes cluster should match the host name.

### CSM Driver(s)

CSI PowerStore

### Installation Type

CSM Operator

### Container Orchestrator

OCP

### Operating System

CoreOS
