### ISSUE TITLE
[BUG]: Unable to mount ReadOnlyMany PVC using CSI driver for PowerFlex

### ISSUE THREAD

**Issue by rishabhatdell** [dell/csm#1565]
### Bug Description

Unable to mount ReadOnlyMany  PVC using CSI-PowerFlex

Error message

```
time="2024-10-21T09:51:06Z" level=info msg="mount command" args="-t ext4 -o ro /dev/scinib /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/2b6e15c75b2ff90f-7ed828f900000025" cmd=mount
time="2024-10-21T09:51:06Z" level=error msg="mount Failed" args="-t ext4 -o ro /dev/scinib /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/2b6e15c75b2ff90f-7ed828f900000025" cmd=mount error="exit status 32" output="mount: /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/2b6e15c75b2ff90f-7ed828f900000025: wrong fs type, bad option, bad superblock on /dev/scinib, missing codepage or helper program, or other error.\n"
```

### Logs

```
time="2024-11-04T11:07:43Z" level=info msg="attempting mount to private area" CSIRequestID=31 device=/dev/scinia id=6689fba68522eb0f-7840b2f70000001f privateMount=/var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f target="/var/lib/kubelet/pods/1e913e9d-6a8b-495d-8337-130b59a76d97/volumes/kubernetes.io~csi/k8s-891444da0e/mount" volumePath=/dev/scinia
time="2024-11-04T11:07:43Z" level=warning msg="Unable to check stat of file: /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f with error: stat /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f: no such file or directory"
time="2024-11-04T11:07:43Z" level=debug msg="created directory" path=/var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f
time="2024-11-04T11:07:43Z" level=info msg="mount command" args="-t ext4 -o ro /dev/scinia /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f" cmd=mount
time="2024-11-04T11:07:43Z" level=error msg="mount Failed" args="-t ext4 -o ro /dev/scinia /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f" cmd=mount error="exit status 32" output="mount: /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f: wrong fs type, bad option, bad superblock on /dev/scinia, missing codepage or helper program, or other error.\n"
time="2024-11-04T11:07:43Z" level=info msg="Cleaning up private target" CSIRequestID=31 privTgt=/var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f
time="2024-11-04T11:07:43Z" level=info msg="/csi.v1.Node/NodePublishVolume: REP 0031: rpc error: code = Internal desc = error performing private mount: mount failed: exit status 32"
time="2024-11-04T11:07:43Z" level=info msg="mounting arguments: -t ext4 -o ro /dev/scinia /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f"
time="2024-11-04T11:07:43Z" level=info msg="output: mount: /var/lib/kubelet/plugins/vxflexos.emc.dell.com/disks/6689fba68522eb0f-7840b2f70000001f: wrong fs type, bad option, bad superblock on /dev/scinia, missing codepage or helper program, or other error."
```

### Steps to Reproduce

- Create Storage Class
- Create ReadOnlyMany PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvol
spec:
    accessModes:
      - ReadOnlyMany
    volumeMode: Filesystem
    resources:
        requests:
            storage: 3Gi
    storageClassName: vxflexos
```
- Create Pod to Consume PVC
```
apiVersion: v1
kind: Pod
metadata:
    name: test-pod
spec:
    containers:
      - name: test
        image: docker.io/centos:latest
        command: [ "/bin/sleep", "3600" ]
        volumeMounts:
          - mountPath: "/data0"
            name: pvol
    volumes:
      - name: pvol
        persistentVolumeClaim:
            claimName: pvol
```

### Expected Behavior

Volume should successfully mount to pod and pod should be running state 

### CSM Driver(s)

CSI-PowerFlex

### Installation Type

Helm/Operator

### Container Orchestrator

OCP/K8s

### Operating System

RHEL
