### ISSUE TITLE
[BUG]: Remove extra fields from the driver specs when using minimal sample

### ISSUE THREAD

**Issue by shanmydell** [dell/csm#1594]
### Bug Description

Manifest file used to deploy CSM 
![image](https://github.com/user-attachments/assets/7d4be0fd-0f03-4e68-b407-bc4380a2f0dd)
Status of the Pod
![image](https://github.com/user-attachments/assets/6587ca97-31dd-4c9b-bae9-7cbd15254b6a)
![image](https://github.com/user-attachments/assets/6277105b-d315-4dd4-adf5-a28e8e5b45a9)

### Logs

![image](https://github.com/user-attachments/assets/3443b5f0-5591-43e6-9bdb-dbdfc6c132ce)

### Steps to Reproduce

Deploy the driver with the simple manifest in description

### Expected Behavior

The request is to ensure no additional fields are populated in the spec unless explicitly provided by the user.

Details:

For example, consider the following YAML applied to the cluster:

```
apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: powerflex
  namespace: powerflex
spec:
  driver:
    csiDriverType: "powerflex"
    configVersion: v2.12.0
```
When running `kubectl get csm powerflex -n powerflex -o yaml`, the resulting output includes additional fields in the spec, as shown below:

```
spec:
  driver:
    common:
      envs:
      - name: KUBELET_CONFIG_DIR
        value: /var/lib/kubelet
    configVersion: v2.12.0
    controller: {}
    csiDriverSpec: {}
    csiDriverType: powerflex
    initContainers:
    - envs:
      - name: MDM
        value: XXXXXXXXX
      name: sdc
    node: {}
    replicas: 2
```
These additional fields (e.g., common.envs, initContainers, replicas, controller, etc.) should not appear in the spec unless explicitly defined in the input YAML.

The expected behaviour is that the spec should only include the fields provided in the input YAML, such as:

```
spec:
  driver:
    csiDriverType: "powerflex"
    configVersion: v2.12.0
```

### CSM Driver(s)

All drivers, tested with PowerStore and PowerFlex

### Container Orchestrator

NA

### Operating System

NA
