### ISSUE TITLE
[BUG]: VolumeSnapshot failed with not enough quota

### ISSUE THREAD

**Issue by petarvranesevic** [dell/csm#1628]
### Bug Description

When creating a VolumeSnapshot, the creation fails with the following error:

`Failed to check and update snapshot content: failed to take snapshot of the volume csi-csi-001-pmax-fdf42318ad-pvctest-000297600499-00160: "rpc error: code = Internal desc = Failed to create snapshot: CreateSnapshot failed with error (csm-authorization: request denied: not enough quota)`

### Logs

**From VolumeSnapshot yaml**

```
status:
  boundVolumeSnapshotContentName: snapcontent-f85405ce-77cc-470e-ba14-1551e74ed9cb
  error:
    message: 'Failed to check and update snapshot content: failed to take snapshot of the volume csi-csi-001-pmax-fdf42318ad-pvctest-000297600499-00160: "rpc error: code = Internal desc = Failed to create snapshot: CreateSnapshot failed with error (csm-authorization: request denied: not enough quota)"'
    time: '2024-12-04T09:04:06Z'
```

**From csm authorization/proxy-server pod**

```
proxy-server-7db86d5bc-bk4gj proxy-server time="2024-12-04T09:08:15Z" level=debug msg="Creating volume snapshot" system_id=000297600499 volume_id=csi-001-pmsn-f85405ce77
proxy-server-7db86d5bc-bk4gj proxy-server time="2024-12-04T09:08:16Z" level=debug msg="Asking OPA..."
proxy-server-7db86d5bc-bk4gj proxy-server time="2024-12-04T09:08:16Z" level=debug opa_response="{{true [] map[csi-csi-001-pmax-fdf42318ad-pvctest:[{csm-authorization 268435456 }]]}}"
proxy-server-7db86d5bc-bk4gj proxy-server time="2024-12-04T09:08:16Z" level=debug msg="Approving request..."
proxy-server-7db86d5bc-bk4gj proxy-server time="2024-12-04T09:08:16Z" level=error msg="approving snapshot request" error="not enough quota"
proxy-server-7db86d5bc-bk4gj proxy-server time="2024-12-04T09:08:16Z" level=debug msg="proxy: writing error" code=500 message="request denied: not enough quota" storage=powermax
```

### Additional Environment Information

**CSMRole CustomRessource yaml**

```
apiVersion: csm-authorization.storage.dell.com/v1
kind: CSMRole
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/part-of: csm-authorization
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: csm-authorization
  name: csm-authorization
spec:
  quota: 256GiB
  systemID: "000297600499"
  systemType: powermax
  pool: SRP_1
```

**PVC from snapshot**

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi-powermax.dellemc.com
    volume.kubernetes.io/selected-node: ux-test-v-compute0.ocp.example.com
    volume.kubernetes.io/storage-provisioner: csi-powermax.dellemc.com
  creationTimestamp: "2024-12-03T12:00:51Z"
  finalizers:
  - kubernetes.io/pvc-protection
  - snapshot.storage.kubernetes.io/pvc-as-source-protection
  name: pvc-san
  namespace: pvctest
  resourceVersion: "138797607"
  uid: fdf42318-ad80-4739-a341-3f0d9e8a0785
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: powermax-xfs
  volumeMode: Filesystem
  volumeName: pmax-fdf42318ad
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4195200Ki
  phase: Bound
```

Total Storage consumption on powermax is 60GB.

### Steps to Reproduce

Create VolumeSnapshot from Openshift console.

### Expected Behavior

VolumeSnapshot gets created.

### CSM Driver(s)

CSM Operator 1.7.0
CSI v2.12.0 for Powermax

### Installation Type

Operator

### Container Storage Modules Enabled

CSM for Authorization v2.0.0

### Container Orchestrator

Openshift 4.16.9

### Operating System

RHEL CoreOS
