### ISSUE TITLE
[BUG]: Unable to provision volumes in Powermax

### ISSUE THREAD

**Issue by moerz1423** [dell/csm#1716]
### Bug Description

We tried to create a volume but the OPA in the authorization server denies the request. This worked before but stopped working after a complete shutdown of the OpenShift cluster due to maintenance. 

### Logs

```
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=info msg="Validating token!"
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="Serving request" Endpoint="<address>" SystemID=000297600499
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="Edit StorageGroup" storage_group=csi-001-Gold-SRP_1-SG
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="Creating volume in StorageGroup" storage_group=csi-001-Gold-SRP_1-SG
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="Create volume request" pvName= sgID=csi-001-Gold-SRP_1-SG spID=SRP_1 systemID=000297600499 volIdName=ux-csi-001-pmax-d3d19c478b-pvctest volSize=2098560
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="Asking OPA..."
proxy-server-7db86d5bc-dk9tq opa {"client_addr":"127.0.0.1:48222","level":"info","msg":"Received request.","req_body":"{\"Host\":\"127.0.0.1:8181\",\"input\":{\"claims\":{\"aud\":\"csm\",\"exp\":1737734026,\"iss\":\"com.dell.csm\",\"sub\":\"csm-tenant\",\"roles\":\"csm-authorization\",\"group\":\"csmtenant-sample\",\"accessExpiration\":\"30m0s\"},\"request\":{\"volumeSizeInKb\":2098560},\"storagepool\":\"SRP_1\",\"storagesystemid\":\"000297600499\",\"systemtype\":\"powermax\"}}\n","req_id":70,"req_method":"POST","req_params":{},"req_path":"/v1/data/karavi/volumes/powermax/create","time":"2025-01-24T15:29:37Z"}
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug opa_response="{}\n"
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug opa_response="{{false [] map[]}}"
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="request denied" reason=
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="proxy: writing error" code=400 message="request denied: " storage=powermax
proxy-server-7db86d5bc-dk9tq opa {"client_addr":"127.0.0.1:48222","level":"info","msg":"Sent response.","req_id":70,"req_method":"POST","req_path":"/v1/data/karavi/volumes/powermax/create","resp_body":"{}\n","resp_bytes":3,"resp_duration":0.265266,"resp_status":200,"time":"2025-01-24T15:29:37Z"}
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=info msg="Serving 10.129.2.2:55584 GET /univmax/restapi/100/sloprovisioning/symmetrix/000297600499/srp/SRP_1/"
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=info msg="Validating token!"
proxy-server-7db86d5bc-dk9tq proxy-server time="2025-01-24T15:29:37Z" level=debug msg="Serving request" Endpoint="https://csm-auth.apps.ux-test.ocp.pva.sozvers.at" SystemID=000297600499
```

### Additional Environment Information

role.yml

```
apiVersion: csm-authorization.storage.dell.com/v1
kind: CSMRole
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: role-sample
    app.kubernetes.io/part-of: csm-authorization
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: csm-authorization
  name: csm-authorization
spec:
  quota: 256GiB
  systemID: <systemID>
  systemType: powermax
  pool: SRP_1
```

storage.yml

```
apiVersion: csm-authorization.storage.dell.com/v1
kind: Storage
metadata:
  name: powermax
spec:
  type: powermax
  endpoint: <unispehere-ip>
  systemID: <systemID>
  vault:
    identifier: vault0
    kvEngine: csm-authorization
    path: storage/powermax/<systemID>
  skipCertificateValidation: true
  pollInterval: 30s
```

tenant.yml

```
apiVersion: csm-authorization.storage.dell.com/v1
kind: CSMTenant
metadata:
  labels:
    app.kubernetes.io/name: csmtenant
    app.kubernetes.io/instance: csmtenant-sample
    app.kubernetes.io/part-of: csm-authorization
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: csm-authorization
  name: csmtenant-sample
spec:
  roles: csm-authorization
  approveSdc: false
  revoke: false
  volumePrefix: ux
```

pvc claim

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  ...
    volume.beta.kubernetes.io/storage-provisioner: csi-powermax.dellemc.com
    volume.kubernetes.io/selected-node: <hostname>
    volume.kubernetes.io/storage-provisioner: csi-powermax.dellemc.com
  creationTimestamp: "2025-01-24T15:27:45Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-san
  namespace: pvctest
  resourceVersion: "206067860"
  uid: d3d19c47-8b02-486e-b888-9e6c10693850
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: powermax
  volumeMode: Filesystem
status:
  phase: Pending
```

storageclass powermax

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2024-12-10T12:47:13Z"
  name: powermax
  resourceVersion: "146834576"
  uid: 523ddbff-0687-4920-b419-ea225c26fd77
parameters:
  SRP: SRP_1
  SYMID: <systemid>
  ServiceLevel: Gold
provisioner: csi-powermax.dellemc.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

### Steps to Reproduce

Create a PVC with storageclass Powermax and a deployment using this PVC.

### Expected Behavior

Volume gets successfully created.

### CSM Driver(s)

CSM Operator 1.7.0
CSI v2.12.0 for Powermax

### Installation Type

Operator

### Container Storage Modules Enabled

CSM for Authorization v2.0.0

### Container Orchestrator

Openshift 4.16.9

### Operating System

RHEL CoreOS
