### ISSUE TITLE
[BUG]: CSM-Operator Bash Install Script Installs Wrong CRD

### ISSUE THREAD

**Issue by falfaroc** [dell/csm#1721]
### Bug Description

On a clean install, when using the `bash scripts/install.sh`, the wrong CRDs are installed for CSM. The one's installed are located in the `deploy` folder but the generated ones that should be used are the one's in the `config` folder. Those CRDs need to be copied into the deploy folder so that the correct CRDs are installed.

**Note:**  This is only an issue when installing `minimal manifest`. In a recent change, a default of `2` has been added to the driver replicas when that field isn't provided. The `minimal manifests` do not provide that field but with the CRDs in the `deploy` folder, that default isn't there so the driver replicas is set to `0`.

### Logs

**When using the CRDs in the Deploy Folder:**
```yaml
Spec:
  Driver:
    Config Version:       v2.13.0
    Csi Driver Type:      powermax
    Force Remove Driver:  true
    Replicas:             0 
```

**When having the correct CRDs installed:**
```yaml
Spec:
  Driver:
    Config Version:       v2.13.0
    Csi Driver Type:      powermax
    Force Remove Driver:  true
    Replicas:             2
```

### Steps to Reproduce

1. Uninstall CSM-Operator and associated CRDs.
2. Install using `bash scripts/install.sh`.
3. Install Driver using `minimal manifest`.
4. Check and see the `driver.replica` set to `0`.

### Expected Behavior

The Driver Replica should display 2 when using `minimal manifest`.

### CSM Driver(s)

All drivers when installing using the `minimal manifest`.

### Container Orchestrator

N/A

### Operating System

N/A
