### ISSUE TITLE
[BUG]: Unity CSI driver customizing TENANT_NAME broken

### ISSUE THREAD

**Issue by dancohen21** [dell/csm#1724]
### Bug Description

Organization has Bare Metal OpenShift 4.16 cluster.
They are using CSM Operator 1.7.0 deploying csi-unity 2.12
Worker nodes are FC connected to Dell Unity XT running supported code level

organization customized TENANT_NAME and the hosts registrations were never made on the unity;  completely broke the deployment.

redeploying with 
        - name: TENANT_NAME
          value: ""

Worked perfectly fine

### Logs

none

### Screenshots

provided on request directly to engineering through dan.cohen@dell.com

### Steps to Reproduce

as described above

### Expected Behavior

expected that the string provided in the TENANT_NAME parameter would be added to the host name used in the Unity XT host registration record.

### CSM Driver(s)

CSM 1.12

### Installation Type

csm-operator 1.7.0

### Container Storage Modules Enabled

n/a

### Container Orchestrator

OpenShift 4.16

### Operating System

coreos

**Comment by csmbot** [comment]
@dancohen21: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and respond appropriately.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at container.storage.modules@dell.com.

**Comment by KshitijaKakde** [comment]
Hi @dancohen21,
The current feature supports only a single tenant for all nodes in the cluster. Users may encounter an error if a PVC is created from a NAS server whose pool is mapped to different tenants not associated with this StorageClass (SC).

For operator-based installation, specify the TENANT_NAME in the ConfigMap as shown in the following example:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: unity-config-params
  namespace: unity
data:
  driver-config-params.yaml: |
    CSI_LOG_LEVEL: "info"
    ALLOW_RWO_MULTIPOD_ACCESS: "false"
    MAX_UNITY_VOLUMES_PER_NODE: "0"
    SYNC_NODE_INFO_TIME_INTERVAL: "15"
    TENANT_NAME: ""
```
