### ISSUE TITLE
[FEATURE]: Document `oc-mirror` for OpenShift offline installation

### ISSUE THREAD

**Issue by coulof** [dell/csm#1768]
**Describe the solution you'd like**
The current & beta version of the documentation explains how to use `scripts/csm-offline-bundle.sh` to build an offline package.

This is not the recommended method for OpenShift. This article explains how to mirror an Operator:
https://www.redhat.com/en/blog/deploying-red-hat-openshift-operators-disconnected-environment

I successfully followed that method with:
```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/certified-operator-index:v4.17
    packages:
    - channels:
      -  minVersion: "1.8.0"
         name: "stable"
      name: "dell-csm-operator-certified"
    targetCatalog: certified-operator-v4.17
storageConfig:
  local:
    path: /tmp/dell-csm-operator-imageset
```

The request is to update the documentation to reflect an offline installation in Openshift context using Openshift recommended method.
