### ISSUE TITLE
[QUESTION]: prometheus-node-exporter Pods in Pending Status due to Port 9100 being in use

### ISSUE THREAD

**Issue by nfonseca** [dell/csm#1783]
Issue:

Followed deployment guide to deploy the CSM Observability Module for PowerStore on Bare Metal OpenShift 4.15.39.
Got the karavi pods deployed and configured correctly. Can see activity from karavi controler logs.
When moving to the next phase of deploying Prometheus from the Helm charts, the prometheus-node-exporter pods are in the Pending status.
Reason for them being in the pending Status is:

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  11m (x539 over 18h)  default-scheduler  0/4 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/4 nodes are available: 1 No preemption victims found for incoming pod, 3 Preemption is not helpful for scheduling..
```

The prometheus-node-exporter Pods need port 9100 from the HostNetwork:

```
Controlled By:    DaemonSet/prometheus-prometheus-node-exporter
Containers:
  node-exporter:
    Image:      quay.io/prometheus/node-exporter:v1.9.0
    Port:       9100/TCP
    Host Port:  9100/TCP
    Args:
```

Port 9100 is used by kube-rbac on the nodes

```
nfonseca@SRVR198052:~/prometheus$ oc get pods -A -o yaml | grep 9100 -B2 | grep -i name
      name: node-exporter
      name: node-exporter
      name: node-exporter
      name: node-exporter
      name: node-resolver
      name: node-resolver
      name: node-resolver
      name: node-resolver
      name: kube-rbac-proxy
      name: kube-rbac-proxy
      name: kube-rbac-proxy
      name: kube-rbac-proxy
nfonseca@SRVR198052:~/prometheus$

```

How can I workaround this ? 

I have tried to reboot the nodes without any luck.

**Comment by nfonseca** [comment]
`oc logs pod/prometheus-prometheus-node-exporter-8g4cd`

```
time=2025-03-04T11:50:52.537Z level=INFO source=node_exporter.go:141 msg=zfs
time=2025-03-04T11:50:52.537Z level=ERROR source=node_exporter.go:247 msg="listen tcp 0.0.0.0:9100: bind: address already in use"

```

**Comment by nfonseca** [comment]
Fixed the issue by editing the daemonset, and providing a different Port other than the default 9100
Changes made:

```
     containers:
      - args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --path.udev.data=/host/root/run/udev/data
        - --web.listen-address=[$(HOST_IP)]:9101 <----------- New Port !
        env:
        - name: HOST_IP
          value: 0.0.0.0
        image: quay.io/prometheus/node-exporter:v1.9.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9101<----------- New Port !
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: node-exporter
        ports:
        - containerPort: 9101<----------- New Port !
          hostPort: 9101<----------- New Port !
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9101<----------- New Port !
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
```
