### ISSUE TITLE
[QUESTION]: kubelet metrics doesn't contain kubelet_volume metrics from powerflex-csi

### ISSUE THREAD

**Issue by TomasKohout** [dell/csm#236]
Hi :slightly_smiling_face: ,

we've noticed that kubelet_volume metrics are gone since upgrade to v2.1.0 of csi-powerflex.

It there anything we can do to make those metrics work?

Thanks a lot. :slightly_smiling_face:

**Comment by TomasKohout** [comment]
1. kubernetes 1.21.9
2.
```yaml
version: 2.1.0-mall.2

images:
  driverRepository: ---redacted----

attacher:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

controller:
  volumeNamePrefix: k8s
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

driver:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

provisioner:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

registrar:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

resizer:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

sdc:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

snapshotter:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1
      memory: 1Gi

```

3. Reinstallation on one cluster, helm upgrade on the other.
4. kubelet_volume_* metrics contains information about PVCs mounted on each worker node.
