### ISSUE TITLE
[BUG]: PowerStore CSI appears to look for iSCSI when FC only is being used

### ISSUE THREAD

**Issue by DougBernhardt** [dell/csm#252]
### Bug Description

attach-controller can't attach volume:
AttachVolume.Attach failed for volume "csivol-61a1cb94f1" : rpc error: code = Internal desc = could not get iscsiTargets: can't get iscsi target address

This is on an FC system.  iSCSI is not configured.  FC only should not be a problem.

I even tried adding the following to a new storage class:
AllowedTopologies:
  Term 0:              csi-powerstore.dellemc.com/xx.xx.xx.xx-fc in [true]

### Logs

AttachVolume.Attach failed for volume "csivol-61a1cb94f1" : rpc error: code = Internal desc = could not get iscsiTargets: can't get iscsi target address

### Steps to Reproduce

create deployment that uses pvc.

### Expected Behavior

volume should attach fine

### CSM Driver(s)

CSI Driver for PowerStore v2.2.0

### Container Orchestrator

Kubernetes v1.23.5

### Operating System

RHEL 8.5

**Comment by shanmydell** [comment]
@francis-nijay : Could you please have a look?

**Comment by francis-nijay** [comment]
Hi @DougBernhardt ,

Can you please let us know the value of blockProtocol from the secret created for csi-powerstore. If iSCSI is mentioned, then the driver will look for iSCSI initiators.

**Comment by DougBernhardt** [comment]
Regardless of the blockProtocol value, it appears to be checking to see if iSCSI has been enabled on the array.  Once I enabled it on the array, then it works.  This is a workaround, but a FC only array should not be required to have iSCSI configured.

**Comment by francis-nijay** [comment]
@DougBernhardt Can you please share controller and node logs to find where the check happens and make a fix if necessary.

**Comment by Daniel-Vaz** [comment]
I currently am encountering this same issue. 

```
Kubernetes Version: v1.22.8
Kubernetes Distribution: Anthos on BareMetal 1.11.0
PowerStore CSI Driver version: 2.2.0
Installation Type: Helm
Nodes OS: Oracle Linux 8.4
``` 

I configured the secret and helm values to deploy de driver using FiberChannel for the connection (please look into the attached files to see the configurations that were used - [values.zip](https://github.com/dell/csm/files/8505832/values.zip)). Then installed the Powerstore CSI driver using Helm, and everything was deployed successfully, and running the `verify.sh` script reports no errors. 

We then proceeded to create a XFS Storage Class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: powerstore-xfs
parameters:
  FsType: xfs
provisioner: csi-powerstore.dellemc.com
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

And a PVC:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvol1
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: powerstore-xfs
```

When we then create a Pod that mounts the previously mentioned PVC locally, we see that a PV gets created and Bound to the PVC correctly but the Pods gets stuck in a ContainerCreating phase with the following logs when described:

```
Warning FailedAttachVolume 40s (x9 over 2m52s)  attachdetach-controller AttachVolume.Attach failed for volume "csivol-ee3218d5c6" : rpc error: code = Internal desc = could not get iscsiTargets: can't get iscsi target address
```

We configured everything to use FC, but the Pod is insisting on using ISCi.
