### ISSUE TITLE
RootClientEnabled: "true" not working  with PowerScale CSI Driver v1.2.0 

### ISSUE THREAD

**Issue by RyanBao** [dell/csm#318]
It's PowerScale H700 storage environment, with K8S cluster v1.16 and Powerscale CSI Driver v1.2.0.

As requested, we need to provide root access to Persistent Volumes in Pods, using the PowerScale CSI Driver previously installed with RootClientEnabled: "false".

Then, we created a new StorageClass, changing RootClientEnabled to "true" as below:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: isilon
    meta.helm.sh/release-namespace: isilon
    storageclass.beta.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: isilon-core
parameters:
  AccessZone: System
  AzServiceIP: service.sycoreisilon.bj.bob
  IsiPath: /ifs/data/csi
  RootClientEnabled: "**true**"
provisioner: csi-isilon.dellemc.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

After the new StorageClass created, and new PVC created and mounted, it showed that the mount point in Pod is still owned by nobody (id 99). From PowerScale H700 UI, both the "Root Client" and "Client" are empty. Look like RootClientEnabled: "true" is not working as expected.

Is there any workaround to fix it? Is it a version issue?

Thanks a lot,
RyanBao
