### ISSUE TITLE
[BUG]: Operator v1.8.0 declares Unity configVersion v2.3.0 as "unknown drive config version"

### ISSUE THREAD

**Issue by jmyoung** [dell/csm#417]
### Bug Description

Running Openshift 4.9, with the Dell-CSI-Operator installed.  Verified that I do indeed have the v1.8.0 operator installed (upgrade policy is set to Automatic).

When following the directions at https://dell.github.io/csm-docs/docs/csidriver/installation/operator/#update-csi-drivers, I changed configVersion from v2.2.0 to v2.3.0 and also updated sidecar and image versions appropriately, when using the CSIUnity driver.  On doing this, the operator declares;

```
2022-08-11T04:36:42.494Z        ERROR   controllers.CSIUnity    Validation error        {"csiunity": "dell-csi-config/unity-prd", "Namespace": "dell-csi-config", "Name": "unity-prd", "Attempt": 467, "error": "unknown driver config version"}
```

And that's that.  I dug into the operator's container, and found the version of https://github.com/dell/dell-csi-operator/blob/v1.8.0/driverconfig/config.yaml that it's using does indeed match the v1.8.0 operator, and it does indeed include configuration for a v2.3.0 CSIUnity configVersion, but it still appears to not work.

### Logs

2022-08-11T06:01:25.766Z        INFO    controllers.CSIUnity    ################End Reconcile##############     {"csiunity": "dell-csi-config-test/unity-test", "Namespace": "dell-csi-config-test", "Name": "unity-test", "Attempt": 6}
2022-08-11T06:02:47.653Z        INFO    controllers.CSIUnity    Reconciling unity       {"csiunity": "dell-csi-config-test/unity-test", "Namespace": "dell-csi-config-test", "Name": "unity-test", "Attempt": 7, "request": "dell-csi-config-test/unity-test"}
2022-08-11T06:02:47.653Z        INFO    controllers.CSIUnity    ################Starting Reconcile##############        {"csiunity": "dell-csi-config-test/unity-test", "Namespace": "dell-csi-config-test", "Name": "unity-test", "Attempt": 7}
2022-08-11T06:02:47.658Z        INFO    controller_config       Reading file for default image tags     {"Filename": "/etc/config/dell-csi-operator/config.yaml"}
2022-08-11T06:02:47.660Z        ERROR   controllers.CSIUnity    Failed to initialize driver config      {"csiunity": "dell-csi-config-test/unity-test", "error": "unknown driver config version"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
2022-08-11T06:02:47.660Z        ERROR   controllers.CSIUnity    Validation error        {"csiunity": "dell-csi-config-test/unity-test", "Namespace": "dell-csi-config-test", "Name": "unity-test", "Attempt": 7, "error": "unknown driver config version"}
github.com/dell/dell-csi-operator/controllers.(*CSIUnityReconciler).Reconcile
        /workspace/controllers/csiunity_controller.go:84
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/internal/controller/controller.go:227
2022-08-11T06:02:47.660Z        INFO    controllers.CSIUnity    Marking the driver status as InvalidConfig      {"csiunity": "dell-csi-config-test/unity-test", "Namespace": "dell-csi-config-test", "Name": "unity-test", "Attempt": 7}
2022-08-11T06:02:47.660Z        INFO    controllers.CSIUnity    No change to status. No updates will be applied to CR status    {"csiunity": "dell-csi-config-test/unity-test", "Namespace": "dell-csi-config-test", "Name": "unity-test", "Attempt": 7}

### Steps to Reproduce

1. Have existing CSIUnity configuration
2. Change configVersion to "v2.3.0"

### Expected Behavior

I expected the upgrade to take place

### CSM Driver(s)

CSI Driver for Unity XT 2.3.0

### Installation Type

Operator v1.8.0

### Container Orchestrator

OpenShift 4.9

### Operating System

RHCOS

**Comment by rensyct** [comment]
Hi @jmyoung 
Could you help share the Unity driver manifest file which was modified

**Comment by jmyoung** [comment]
```yaml
apiVersion: storage.dell.com/v1
kind: CSIUnity
metadata:
  name: unity-test
  namespace: dell-csi-config-test
spec:
  driver:
    configVersion: v2.3.0
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    common:
      image: "dellemc/csi-unity:v2.3.0"
      imagePullPolicy: IfNotPresent
    sideCars:
      - name: provisioner
        args: ["--volume-name-prefix=unityocpblue","--default-fstype=ext4"]
      - name: snapshotter
        args: ["--snapshot-name-prefix=unityocpbluesnap"]
    controller:
       nodeSelector:
         node-role.kubernetes.io/infra: ""
    node:
       envs:
          # Set to 'true' to enable full debug logging
          - name: X_CSI_DEBUG
            value: "false"
```

Note that this happens whether this is an upgrade (ie, by editing the existing manifest), or when creating this manifest fresh.
