### ISSUE TITLE
[QUESTION]:How to scrape CSM Observability with openshift-monitoring

### ISSUE THREAD

**Issue by grvn** [dell/csm#707]
### How can the Team help you today?

**Details: ?**
OpenShift comes with an internal observability stack out-of-the-box with a prometheus.
It uses annotations and labels to register endpoints to scrape.

https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/monitoring/index

How should we configure CSM observability to be scraped by the cluster-monitoring in OpenShift?

**Comment by grvn** [comment]
I tried setting the label `openshift.io/cluster-monitoring=true` on the namespace but that didn't seem to work.

**Comment by baoy1** [comment]
We have no experience in that. Maybe you can try installing CSM Observability to the same namespace as prometheus.

**Comment by grvn** [comment]
OpenShift installs prometheus out-of-the-box in the namespace `openshift-monitoring` which is controlled by a clusteroperator so installing in the same namespace isn't recommended by Red Hat.
The label `openshift.io/cluster-monitoring=true` allows pods ( prometheus ) in the `openshift-monitoring` namespace to access other namespaces which is otherwise blocked by a NetworkPolicy.

I think https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/monitoring/index can be helpful and might provide an answer but it would be nice with some guidelines/How-To from Dell if possible.

There is a PodMonitor and a ServiceMonitor CRD in the prometheus-operator ( and openshift-monitoring clusteroperator ) which might be useful.
https://github.com/openshift/prometheus-operator/blob/release-4.12/Documentation/api.md

**Comment by baoy1** [comment]
We are having a discussion. Will come back to your later. Please stay tuned. Thanks!

**Comment by donatwork** [comment]
@grvn We will have to test this in house and may be delayed in doing so. The goal is to get the OpenShift Prometheus to scrape from the CSM OTEL collector. There should be some similar approach that we documented (https://dell.github.io/csm-docs/docs/observability/deployment/#prometheus-helm-deployment) to get Prometheus configured. So you can apply the label and add the scrape config...in theory. We need to schedule testing on our end and that will take some time.

**Comment by OA72280** [comment]
Specific to OpenShift you can use the existing Prometheus instance to monitor user-defined workloads - https://docs.openshift.com/container-platform/4.11/monitoring/enabling-monitoring-for-user-defined-projects.html

Once you've enabled this you can deploy grafana... When deploying grafana using the grafana operator I'd be interested in knowing who has successfully used the init-container to wedge in the additional plugins required.

**Comment by lukeatdell** [comment]
Thanks for your patience, @grvn.

1. As @OA72280 commented above, begin by following the instructions in the provided link to enable user workload monitoring.
2. Follow the [official documentation](https://dell.github.io/csm-docs/docs/) to install your csi-driver and csm-observability.
3. You'll want to create a 'route' to the karavi-topology service created when observability was installed. This is most easily accomplished using the OpenShift Console. Make sure to configure the route as 'secure' and select 'Passthrough' as TLS termination.
4. Next you'll want to install Grafana. I found the easiest way to do this was to use the Grafana Operator, again using the OpenShift Console.
    - Install the Grafana Operator in the openshift-user-defined-workload namespace.
5. To include the plugins with the initial deployment, create a configMap in the openshift-user-defined-workload namespace.
    - Name it 'grafana-plugins' and set the key to 'GF_INSTALL_PLUGINS'.
    - Enter into the Values box a comma-separated list of the desired plugins. e.g. 'grafana-simple-json-datasource,briangann-datatable-panel,grafana-piechart-panel'
6. Create an instance of Grafana using the Grafana Operator.
    - Configure the admin user and password.
    - Expand Deployment > envFrom and enter the name 'grafana-plugins', referencing the configMap created earlier.
    - Set the baseImage to 'docker.io/grafana/grafana:8.5.0'
    - Expand Service and set the type to 'NodePort'.
7. Create a route to the grafana-service created with the Grafana instance.
8. Grant cluster monitoring permissions to grafana-serviceaccount and get a token.
    - I used: `oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount -n openshift-user-workload-monitoring`
    - Create an access token: `oc create token grafana-serviceaccount -n openshift-user-workload-monitoring`
9. Create a GrafanaDataSource instance using the Grafana Operator.
    - Example Config:
```
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: test-datasource
  namespace: openshift-user-workload-monitoring
spec:
  datasources:
    - access: proxy
      editable: true
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: >-
          Bearer
          {INSERT_BEARER_TOKEN}
      type: prometheus
      url: >-
        https://{INSERT_THANOS_QUERIER_SERVICE}:9091
      version: 1
    - access: proxy
      editable: true
      jsonData:
        tlsSkipVerify: true
      name: Karavi-Topology
      type: grafana-simple-json-datasource
      url: {INSERT_TOPOLOGY_ROUTE}
      version: 1
  name: datasources.yaml
```
    - In the config, substitute the token created in the last step, the route to karavi-topology, and the service for the thanos-querier in namespace, openshift-monitoring.
10. Create a ServiceMonitor to expose the metrics.
      - Copy the [example ServiceMonitor config](https://dell.github.io/csm-docs/docs/observability/deployment/#prometheus-helm-deployment) from the official documentation, making any necessary changes.
      - `kubectl create -f <your-ServiceMonitorConfig.yaml>` to create the ServiceMonitor.
11. Navigate to your Grafana console using the route created earlier.
      - Verify the data sources are working as expected.
      - Import the dashboards using the [instructions from the documentation.](https://github.com/dell/karavi-observability/tree/main/grafana/dashboards)

If you're having trouble accessing any aspects of the console, be sure to add your IP and FQDN to the etc/hosts file of the machine you're using to obtain access.

Please, let us know if this helps.
