### ISSUE TITLE
[BUG]:  Unable to start up driver pods on both node and controller. 

### ISSUE THREAD

**Issue by ribua** [dell/csm#723]
### Bug Description

We recently installed the version 2.5.0 on our openshift 4.10.41 clusters , however the driver container fails to start up due to the array not being found. This was working fine in version 2.3.0  , however the recent upgrade to 4.10.x seems to have caused it with the additional environment variable of the csipowermaxrevproxies.storage.dell.com. I will include the details leading to the issue. 

[1] Installed the version 2.5.0 
[2] Created a default CSIPowerMaxRevProxy with the name powermax-reverseproxy from the UI console of OpenShift. 
[3] Created the CR for CSIPowermax with the default options including the below options 

Below is the spec file used for the same 

```yaml
spec:
  driver:
    common:
      envs:
        - name: X_CSI_MANAGED_ARRAYS
          value: '000297600224'
        - name: X_CSI_POWERMAX_ENDPOINT
          value: 'https://00.00.00.00:8443/'
        - name: X_CSI_K8S_CLUSTER_PREFIX
          value: 'XXX'
        - name: X_CSI_POWERMAX_PORTGROUPS
          value: ''
        - name: X_CSI_TRANSPORT_PROTOCOL
          value: 'FC'
        - name: X_CSI_POWERMAX_PROXY_SERVICE_NAME
          value: 'powermax-reverseproxy'
        - name: X_CSI_GRPC_MAX_THREADS
          value: '4'
        - name: X_CSI_VSPHERE_ENABLED
          value: 'false'
        - name: X_CSI_VSPHERE_PORTGROUP
          value: ''
        - name: X_CSI_VSPHERE_HOSTGROUP
          value: ''
        - name: X_CSI_VCenter_HOST
          value: ''
        - name: X_CSI_VCenter_USERNAME
          value: ''
        - name: X_CSI_VCenter_PWD
          value: ''
      image: >-
        docker.io/dellemc/csi-powermax@sha256:5c62f67c45bb480ea0070ca88223089e13e9a38963f6d85ba77fd25b77608ef5
      imagePullPolicy: IfNotPresent
    configVersion: v2.5.0
    controller:
      nodeSelector: null
      tolerations: null
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    node:
      envs:
        - name: X_CSI_POWERMAX_ISCSI_ENABLE_CHAP
          value: 'false'
        - name: X_CSI_TOPOLOGY_CONTROL_ENABLED
          value: 'false'
      nodeSelector: null
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/memory-pressure
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/disk-pressure
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/network-unavailable
          operator: Exists
    replicas: 2

```

[4] The controller and node driver container reporting errors. 

### Logs

```bash
$ oc logs -f powermax-controller-6564bf8855-prkx2 driver
I0322 05:02:25.017762       1 leaderelection.go:242] attempting to acquire leader lease  dell-powermax-csi/driver-csi-powermax-dellemc-com...
I0322 05:02:53.311465       1 leaderelection.go:252] successfully acquired lease dell-powermax-csi/driver-csi-powermax-dellemc-com
time="2023-03-22T05:02:53Z" level=info msg="Read CSI_LOG_FORMAT: json from configuration file"
time="2023-03-22T05:02:53Z" level=info msg="Read CSI_LOG_LEVEL: debug from config file"
{"level":"info","msg":"Setting log level to debug","time":"2023-03-22T05:02:53.312169909Z"}
{"level":"debug","msg":"setting GrpcMaxThreads to 4","time":"2023-03-22T05:02:53.312254299Z"}
{"level":"debug","msg":"Entering controllerProbe","time":"2023-03-22T05:02:53.312277617Z"}
{"level":"debug","msg":"Portgroups length is: 0","time":"2023-03-22T05:02:53.312283322Z"}
{"level":"info","msg":"Successfully started the lock request handler","time":"2023-03-22T05:02:53.312287848Z"}
{"error":null,"level":"error","msg":"Unable to parse Unisphere timout","time":"2023-03-22T05:02:53.31229615Z"}
{"applicationName":"CSI Driver for Dell EMC PowerMax/v2.5.0","debug":true,"endpoint":"https://100.119.194.104:2222","insecure":true,"level":"debug","logResponseTimes":false,"msg":"pmax client init","time":"2023-03-22T05:02:53.312349702Z","useCerts":true,"version":"100"}
{"level":"info","msg":"PowerMax debug: true","time":"2023-03-22T05:02:53.312369186Z"}
{"level":"debug","msg":"username: xxxxxxxxxx , password: *****","time":"2023-03-22T05:02:53.312394774Z"}
{"level":"debug","msg":"\n    -------------------------- POWERMAX HTTP REQUEST -------------------------\n    GET /univmax/restapi/version HTTP/1.1\n    Host: 100.119.194.104:2222\n    \n","time":"2023-03-22T05:02:53.31241383Z"}
{"level":"info","msg":"CleanupMapEntries: Successfully started the cleanup worker. This will wake up every 240.00 minutes to clean up stale entries","time":"2023-03-22T05:02:53.312314394Z"}
{"level":"debug","msg":"\n    -------------------------- POWERMAX HTTP RESPONSE -------------------------\n    HTTP/1.1 200 OK\n    Content-Security-Policy: default-src 'self'\n    Content-Type: application/json\n    Date: Wed, 22 Mar 2023 05:11:07 GMT\n    Referrer-Policy: no-referrer-when-downgrade\n    Restapi-Active-Session-Count: 1\n    Restapi-Processing-Time: 7\n    Strict-Transport-Security: max-age=31536000; includeSubDomains\n    U4v-Shardproxy-Time: 0\n    X-Content-Security-Policy: default-src 'self'\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: SAMEORIGIN\n    X-Webkit-Csp: default-src 'self'\n    X-Xss-Protection: 1; mode=block\n    \n    {\"version\":\"V9.2.3.15\"}\n","time":"2023-03-22T05:02:53.32687262Z"}
{"level":"info","msg":"authentication successful","time":"2023-03-22T05:02:53.326892281Z"}
{"level":"debug","msg":"username: xxxxxxxxxx , password: *****","time":"2023-03-22T05:02:53.326924854Z"}
{"level":"debug","msg":"\n    -------------------------- POWERMAX HTTP REQUEST -------------------------\n    GET /univmax/restapi/100/system/symmetrix/000297600224 HTTP/1.1\n    Host: 100.119.194.104:2222\n    Accept: application/json;version=100\n    Application-Type: CSI Driver for Dell EMC PowerMax/v2.5.0\n    Content-Type: application/json;version=100\n    \n","time":"2023-03-22T05:02:53.326944447Z"}
{"level":"debug","msg":"\n    -------------------------- POWERMAX HTTP RESPONSE -------------------------\n    HTTP/1.1 404 Not Found\n    Content-Security-Policy: default-src 'self'\n    Date: Wed, 22 Mar 2023 05:11:07 GMT\n    Referrer-Policy: no-referrer-when-downgrade\n    Strict-Transport-Security: max-age=31536000; includeSubDomains\n    U4v-Shardproxy-Time: 0\n    X-Content-Security-Policy: default-src 'self'\n    X-Content-Type-Options: nosniff\n    X-Frame-Options: SAMEORIGIN\n    X-Webkit-Csp: default-src 'self'\n    X-Xss-Protection: 1; mode=block\n    Content-Length: 0\n    \n","time":"2023-03-22T05:02:53.332790928Z"}
{"level":"error","msg":"Failed to fetch details for array: 000297600224. [Not Found]","time":"2023-03-22T05:02:53.332834558Z"}
{"level":"error","msg":"None of the managed arrays specified are locally connected","time":"2023-03-22T05:02:53.332849181Z"}

```

### Screenshots

![image](https://user-images.githubusercontent.com/41564422/226807599-15a54aa6-379f-4d65-b2b4-fb4d9569a5f7.png)

![image](https://user-images.githubusercontent.com/41564422/226807697-ce0c851d-596b-40e1-872d-43e5983240f7.png)

### Steps to Reproduce

[1] Installed the version 2.5.0 
[2] Created a default CSIPowerMaxRevProxy with the name powermax-reverseproxy from the UI console of OpenShift. 
[3] Created the CR for CSIPowermax with the default options including the below options 

Presently we have rolled back to the older version of v2.3.0 where it works without adding the revproxy. 

### Expected Behavior

The controllers and node pods to up and running . 

### CSM Driver(s)

CSI Driver for Powermax V2.5.0

dell-csi-operator-certified.v1.10.0

### Installation Type

Operator

### Container Orchestrator

Kubernetes 1.23

### Operating System

CORE OS
