### ISSUE TITLE
how to i solve this error ? level=fatal msg="grpc failed" error="invalid value for IsDefault at index [1] 

### ISSUE THREAD

**Issue by farhadkh000** [dell/csm#759]
### How can the Team help you today?

 i have k8s cluster with one controler node and tow worker node 
```
# k get node
NAME                STATUS   ROLES           AGE    VERSION
master-01.fns.com   Ready    control-plane   219d   v1.26.3
worker-01.fns.com   Ready    <none>          219d   v1.26.3
worker-02.fns.com   Ready    <none>          219d   v1.26.3
```
and i used UnityVSA Community Edition  for test csi driver
 this link for install csi driver unity 
https://dell.github.io/csm-docs/docs/csidriver/installation/helm/unity/ 
but i get this error in unity-node pods  after  deploy all of them 
```
# k logs -f  unity-node-4mjfn  -n unity
Defaulted container "driver" out of: driver, registrar
Endpoint /var/lib/kubelet/plugins/unity.emc.dell.com/csi_sock
time="2023-04-13T20:52:50Z" level=info  runid=start msg="Driver Mode:node" func="github.com/dell/csi-unity/service.(*service).BeforeServe()" file="/go/src/csi-unity/service/service.go:188"
csi-unity logger initiated. This should be called only once.
time="2023-04-13T20:52:50Z" level=info  runid=start msg="X_CSI_UNITY_NODENAME: worker-01.fns.com" func="github.com/dell/csi-unity/service.(*service).BeforeServe()" file="/go/src/csi-unity/service/service.go:196"
time="2023-04-13T20:52:50Z" level=info  runid=config-0 msg="*************Synchronizing driver secret**************" func="github.com/dell/csi-unity/service.(*service).syncDriverSecret()" file="/go/src/csi-unity/service/service.go:473"
time="2023-04-13T20:52:50Z" level=info msg="configured csi-unity.dellemc.com" ArrayId=virt23155ly57z Endpoint="https://192.168.0.132/" IsDefault=true SkipCertificateValidation=true password="*******" username=k8s
time="2023-04-13T20:52:50Z" level=info  runid=config-0 msg="configured csi-unity.dellemc.com" func="github.com/dell/csi-unity/service.(*service).BeforeServe.func1()" file="/go/src/csi-unity/service/service.go:183"
time="2023-04-13T20:52:50Z" level=info msg="removed sock file" path=/var/lib/kubelet/plugins/unity.emc.dell.com/csi_sock
time="2023-04-13T20:52:50Z" level=fatal msg="grpc failed" error="invalid value for IsDefault at index [1]"

```
all pods get error `CrashLoopBackOff`
```
NAME                                READY   STATUS             RESTARTS      AGE
unity-controller-5dbdf79b76-szzr6   4/5     CrashLoopBackOff   6 (44s ago)   7m
unity-node-4mjfn                    1/2     CrashLoopBackOff   6 (46s ago)   7m
unity-node-bjgtm                    1/2     CrashLoopBackOff   6 (51s ago)   7m

```
this is config for my  secret.yaml file 
```
storageArrayList:
  - arrayId: "VIRT23155LY57Z"
    username: "k8s"
    password: "P@ssw0rd"
    endpoint: "https://192.168.0.132/"
    skipCertificateValidation: true
    isDefault: true

  - arrayId: "VIRT23155LY57Z"
    username: "k8s"
    password: "P@ssw0rd"
    endpoint: "https://192.168.0.132/"
    skipCertificateValidation: true
```
How can I fix this problem?

**Comment by atye** [comment]
Hi @farhadkh000, we will look into this. In the meantime, could you try setting the `isDefault` field to `false` for the second array with ID VIRT23155LY57Z?

**Comment by farhadkh000** [comment]
> Hi @farhadkh000, we will look into this. In the meantime, could you try setting the `isDefault` field to `false` for the second array with ID VIRT23155LY57Z?
Thank you for your attention 
but i change setting secret.yaml file with this parameters and solved problem: 
```
storageArrayList:
  - arrayId: "VIRT23155LY57Z"
    username: "k8s"
    password: "P@ssw0rd"
    endpoint: "https://192.168.0.132/"
    skipCertificateValidation: true
    isDefault: true
```
