### ISSUE TITLE
[BUG]: Replication install using Operator does not work

### ISSUE THREAD

**Issue by donatwork** [dell/csm#788]
### Bug Description

It is not possible to install CSM Replication in the single stretched cluster mode. The parameter TARGET_CLUSTER_IDS requires at least one value but in the repctl instructions the target cluster is replaced with "self". This does not work when using Operator.

 ```
     - name: dell-replication-controller-manager
        # image: Defines controller image. This shouldn't be changed
        # Allowed values: string
        image: dellemc/dell-replication-controller:v1.4.0
        envs:
          # TARGET_CLUSTERS_IDS: comma separated list of clusters id of the targets clusters. DO NOT include the source(wherever CSM Operator is deployed) cluster id
          # Allowed values: string
          - name: "TARGET_CLUSTERS_IDS"
            value: "self"
```

Also tried with an empty value "" and also saw errors.

Another issue I have with the documentation is that the instructiosn (https://dell.github.io/csm-docs/docs/deployment/csmoperator/modules/replication/#prerequisite) states to follow all of the steps in the install using repctl section but those instructions install an instance of the dell-replication-controller-manager. Why is the Operator installation also installing the same pod?

### Logs

`Event(v1.ObjectReference{Kind:"ContainerStorageModule", Namespace:"isilon", Name:"isilon", UID:"44538889-bfe8-4dae-aae1-63959c9d73de", APIVersion:"storage.dell.com/v1", ResourceVersion:"892885", FieldPath:""}): type: 'Warning' reason: 'Updated' Failed Prechecks: failed replication validation: TARGET_CLUSTERS_IDS on CR should have more than 0 commma seperated cluster IDs. Got  0
`

### Steps to Reproduce

Attempt to follow the documentation to install CSM-Replication on a single "stretched" cluster.

### Expected Behavior

I expect either "self" or "" to be accepted as valid when installing in stretched clsuter mode.

### CSM Driver(s)

CSI Driver for PowerScale v2.6.0

### Installation Type

CSM-Operater 1.1.0

### Container Orchestrator

Kubernetes v1.25.6

### Operating System

RHEL 8.7-2
