### ISSUE TITLE
[BUG]: Topology based scheduling does not work when recreating Statefulsets

### ISSUE THREAD

**Issue by skavyas** [dell/csm#81]
**Describe the bug**
Topology based scheduling is not working when recreating Statefulsets.
**To Reproduce**
1. Create StorageClass with 
```
allowedTopologies:
- matchLabelExpressions:
  - key: "csi-vxflexos.dellemc.com/340906774c30210f
    values:
    - csi-vxflexos.dellemc.com
```
and 
```
volumeBindingMode: WaitForFirstConsumer
```
NOTE - Powerflex is deployed/installed only on a subset of nodes in the cluster
2. Create a Statefulset without nodeAffinity, pods are scheduled on the right nodes
3. Delete the Statefulset created in step2.
4.  Recreate the Statefulset created in step2.
5. The pods are scheduled on nodes where powerflex is not installed

**Expected behavior**
Pods are scheduled on nodes where Powerflex is installed, even after re-creating the statefulset

**Logs**
Controller logs - https://gist.github.com/skavyas/6e155d1cff3dc0c75ff039d0142b80a4

**System Information (please complete the following information):**
 - OS/Version: [e.g. RHEL 7.9]
 - Kubernetes Version [e.g. 1.19]
